### ISSUE TITLE
Crash upon clicking "Reload Avatar"

### ISSUE THREAD

**Issue by HexBugOrion** [TheOneTrueZandra/Figura#1]
Title says it all.

[crash-2021-03-25_16.43.13-client.txt](https://github.com/TheOneTrueZandra/Figura/files/6208008/crash-2021-03-25_16.43.13-client.txt)

**Comment by Dolphin2Point1** [comment]
https://github.com/TheOneTrueZandra/Figura/blob/45d2e5b6e2037e3a796ed33c0ad474ce2f5b2f5f/src/main/java/net/blancworks/figura/gui/FiguraTrustScreen.java#L126 problematic line of code. it seems it is trying to cast this to a playerlistwidget

**Comment by HexBugOrion** [comment]
hm fascinating

**Comment by TheOneTrueZandra** [comment]
Yeah. I'll add a simple check for that, it'll be fixed soon. Thanks for reporting.

**Comment by HexBugOrion** [comment]
Thanks again!

**Comment by TheOneTrueZandra** [comment]
Fixed in [this change.](https://github.com/TheOneTrueZandra/Figura/commit/4380e0a15b49f9c69d5ed96a6e0dded817cb0621#diff-7afbbc490fa97f965e1cd0f1f20ab5b782b282efa2be13af5be7734cae57fb95R127)
