### ISSUE TITLE
Rotated cubes render farther left then where they are in blockbench 

### ISSUE THREAD

**Issue by CookiesSleepy** [TheOneTrueZandra/Figura#10]
![unknown](https://user-images.githubusercontent.com/52550063/112648382-d98da080-8e1f-11eb-825d-d0a47ccfaa24.png)
![2021-03-26_05 28 48](https://user-images.githubusercontent.com/52550063/112648390-dd212780-8e1f-11eb-9111-e8ebc6c544aa.png)
the cookie cubes and black "string" cubes all have a rotation of 2.5 on the z axis 

![](https://cdn.discordapp.com/attachments/805969743945269261/825013765635702865/unknown.png)

bbmodel+png 

[bbmodel.zip](https://github.com/TheOneTrueZandra/Figura/files/6212562/bbmodel.zip)

**Comment by TheOneTrueZandra** [comment]
Fixed in 0.0.3 / [this commit](https://github.com/TheOneTrueZandra/Figura/commit/99912d2c9e000daba01c17048c6516af7f47d69b)

**Comment by CookiesSleepy** [comment]
its not fixed :l
