### ISSUE TITLE
Backend crashing whenever i change something in nameplate.setText()

### ISSUE THREAD

**Issue by ThemovieaYT** [TheOneTrueZandra/Figura#104]
I don't think that this is a coincidence that the backend just dies when I save my script, which has changes in nameplate.setText(). It had happened to me 2 times in a row in the Figura MC server.

I really hope you look into this issue.

**Comment by TheOneTrueZandra** [comment]
I appreciate the effort at help, but there is no way that your script setting your nameplate has any effect on the backend.

**Comment by ThemovieaYT** [comment]
oh thought it was the scripting problem lol
