### ISSUE TITLE
Model is rendering on top of the player model's head

### ISSUE THREAD

**Issue by Psilomush** [TheOneTrueZandra/Figura#106]
![image](https://user-images.githubusercontent.com/83923476/117584480-8f315c00-b10d-11eb-828f-e20adf8a7317.png)

I dunno why.. help

**Comment by Anfauglir-Jakob** [comment]
Try moving the model -24 down and save it again. This should render the model on the correct height.

**Comment by Psilomush** [comment]
> Try moving the model -24 down and save it again. This should render the model on the correct height.

![image](https://user-images.githubusercontent.com/83923476/117585311-09fc7600-b112-11eb-9410-13cb587d1f61.png)

The player model is still there

**Comment by Anfauglir-Jakob** [comment]
To deactivate the playermodel you need to use a .lua script which disables the vanilla model.
I would recommend joining the Discord for help with this. In the #avatar-code channel you can find the needed code and its easier to ask for help in the #creation-help channel.

**Comment by Psilomush** [comment]
> To deactivate the playermodel you need to use a .lua script which disables the vanilla model.
> I would recommend joining the Discord for help with this. In the #avatar-code channel you can find the needed code and its easier to ask for help in the #creation-help channel.

I don't really use discord. Could you give me a link to the script?

**Comment by Psilomush** [comment]
That did the trick! Thank you :)
