### ISSUE TITLE
(v0.0.5a) vanilla_part.getRot() fails if the value it gets is nil

### ISSUE THREAD

**Issue by SnaveSutit** [TheOneTrueZandra/Figura#108]
Figura Version: 0.0.5a

The vanilla_model.part.getRot() function returns an error when called. It seems this error is caused by the recent vector lib changes going by the error message.

This happens with any vanilla_model.part

```
function tick()
  local test = vanilla_model.LEFT_LEG
  for k,v in pairs(test) do
	  log(k)
  end
  log(test.getRot())
end
```

![image](https://user-images.githubusercontent.com/28514936/118032931-309af680-b336-11eb-9739-eef119e3ab63.png)

**Comment by TheOneTrueZandra** [comment]
Oh, this was fixed in my last commit.
