### ISSUE TITLE
Toggles Discussion (Ping System)

### ISSUE THREAD

**Issue by ColdIce1605** [TheOneTrueZandra/Figura#119]
Many Avatars use toggles such as double shifting, and items in there hand, why not have a API to support this with a key-bind, and a way to select it and F3 and N.

**Comment by ColdIce1605** [comment]
As I don't know lua well someone should decide what that should look like in lua.

**Comment by BasiqueEvangelist** [comment]
> Many Avatars use toggles such as double shifting, and items in there hand, why not have a API to support this with a key-bind, and a way to select it and F3 and N.

Isn't this what the Pings system is meant to do?

**Comment by ColdIce1605** [comment]
Haven't seen it. Can you give me a link?

**Comment by ColdIce1605** [comment]
> 
> 
> > Many Avatars use toggles such as double shifting, and items in there hand, why not have a API to support this with a key-bind, and a way to select it and F3 and N.
> 
> Isn't this what the Pings system is meant to do?

No its not because unlike the pings system this one is executed arbitrarily: ie what ever the script wants to do to trigger it which unlike the ping system(the name implies that it can't have arbitrary execution based on script).

**Comment by SekoiaTree** [comment]
I definitely wouldn't mind a "sequence detection" API, but I don't think this is necessary for what you're describing. The ping system will also allow you to use keybinds directly instead of sequences like that.

**Comment by ColdIce1605** [comment]
yeah we can change the issue to that, but the ping system trello doesn't have the keybinds on the system and there can still be used to influence how the ping system handles keybinds ie, scrolling(something like F3+N) to limit the wasted space.

**Comment by Francy-chan** [comment]
a keybinding system will be inplemented with pings

**Comment by Manuel-3** [comment]
I imagine the keybinds to work like regular mod / vanilla keybinds, so you can have code triggered by pressing a key. So lets say there are like 9 "slots" for keybinds available in the controls menu (or an infinite amount if that is easy to implement) and you can just assign any keys to them, and in lua you can listen for `keybindEvent1-9` or something like that. Maybe also allow 2 keys as combination to be set, like ctrl+h, so it works when using a lot of different mods and when most keys are already in use

**Comment by TheOneTrueZandra** [comment]
The issue with this idea is the fact that input isn’t synced, you’d be exclusively locked to specifically shifting, moving, arm swinging, and other animations that are synced. Pings will add proper keybinds later, which would just be the preference anyway.

**Comment by Manuel-3** [comment]
Yeah, if not clear, I was referring to the ping system

**Comment by ColdIce1605** [comment]
Renamed the title to more accurately describe what the issue has turned into.

**Comment by ColdIce1605** [comment]
A list of what has gone on 

> I imagine the keybinds to work like regular mod / vanilla keybinds, so you can have code triggered by pressing a key. So lets say there are like 9 "slots" for keybinds available in the controls menu (or an infinite amount if that is easy to implement) and you can just assign any keys to them, and in lua you can listen for `keybindEvent1-9` or something like that. Maybe also allow 2 keys as combination to be set, like ctrl+h, so it works when using a lot of different mods and when most keys are already in use

> yeah we can change the issue to that, but the ping system trello doesn't have the keybinds on the system and there can still be used to influence how the ping system handles keybinds ie, scrolling(something like F3+N) to limit the wasted space.


These are the two ways discussed in this issue.

**Comment by TheOneTrueZandra** [comment]
Oh yeah, thanks for bringing this up again.


Fran is currently working on a system for it whereby scripts can register keybinds (with a default key and a name)

We'll then have an in-game menu that simply lists all registered keybinds for your current avatar, and allows you to fully edit and change them.

Pings are also "done" more or less, which should allow anything you'd need with this to be resolved.

**Comment by ColdIce1605** [comment]
Thanks.
