### ISSUE TITLE
Block groups aren't recognized in game

### ISSUE THREAD

**Issue by nexusgenesis535** [TheOneTrueZandra/Figura#12]
![Untitled](https://user-images.githubusercontent.com/81386004/112670946-ccbc7d00-8e1e-11eb-926e-a30e1e625ecc.png)
Blockbench file on the right, how it looks in game on the left

[ng535.zip](https://github.com/TheOneTrueZandra/Figura/files/6213436/ng535.zip)
Blockbench model^^

**Comment by nexusgenesis535** [comment]
EDIT: This might not be true, the underlying issue seems to be that the pivot point isn't recognized. Sorry for the confusion 😅

**Comment by nexusgenesis535** [comment]
after some testing, ive figured out that this might be intended: the pivot point is not what it seems in blockbench, in blockbench theyre absolute coordinates. but in game, theyre relative to the block

**Comment by TheOneTrueZandra** [comment]
This is actually an issue, and will be fixed in 0.0.3.

Figura should import BlockBench models 1:1 with no exceptions (aside from the one-texture limit). Any other behavior is a bug

**Comment by TheOneTrueZandra** [comment]
Fixed in 0.0.3 / [this commit](https://github.com/TheOneTrueZandra/Figura/commit/99912d2c9e000daba01c17048c6516af7f47d69b)
