### ISSUE TITLE
Scripting unreliable when refrencing certain api calls

### ISSUE THREAD

**Issue by kalkronline** [TheOneTrueZandra/Figura#121]
### THIS IS A HUGE ISSUE

Certain apis are not always available to the script when one might expect them to be, causing huge failure and major bugs down the line.

For instance, dying in first person in singleplayer with your hand visible will cause the player api to be nil for a short period of time. Any calls using player in the render script (which is common) will majorly fail. Another example is the elytra_model api. Initial script load doesn't have the api ready for the player to use, and of course, crashes with an attempt to index ? in a multiplayer setting.

This has probably been an issue for a bit, but recent changes in 0.0.5b have caused this problem to occur more frequently (READ: ALL THE TIME). Any model that disables elytra (a lot) die on load, with the only fix being to manually go into trust menu and reset individual players.

Additionally, when one of the above issues occurs, subsequent uploads of ANY OTHER MODEL FAIL ALSO (when viewing from another players perspective). I'll attach a model that will allow you to demonstrate this occurring.

[huge_phantom.zip](https://github.com/TheOneTrueZandra/Figura/files/6530202/huge_phantom.zip)

**Comment by TheOneTrueZandra** [comment]
This is mostly due to some changes I made so that scripts didn’t have to re-load every time the player entity was recreated. Thanks for making an issue for it! It’s a known bug

**Comment by TheOneTrueZandra** [comment]
We haven't fixed the "original" bug really here, but errors shouldn't be thrown anymore as of 

[https://github.com/TheOneTrueZandra/Figura/commit/96d7c9b5b312692a242e0d85a06635a6854ef319](url)
