### ISSUE TITLE
Figura pre-release (figura-0.0.5c-pre10) Incompatible with Immersive Portals

### ISSUE THREAD

**Issue by FlamesEC** [TheOneTrueZandra/Figura#124]
By trying to open Immersive portals and This figura pre-release, the game crashes while opening

(https://user-images.githubusercontent.com/72460263/119868613-e0e72e00-bee4-11eb-9890-25be652c0965.png)

**Comment by ImperatorStorm** [comment]
crash.txt?

**Comment by Francy-chan** [comment]
It might be a incompatibility with another mod, because cannot reproduce
![image](https://user-images.githubusercontent.com/40085587/119872174-8e643c80-bef9-11eb-8e34-5b182aaed30a.png)

**Comment by FlamesEC** [comment]
Hmmmmmm, what fabric version are you using?

**Comment by Francy-chan** [comment]
Fabric 0.11.3
Fabric API 0.33.0
Immersive Portals 0.90
Figura 0.0.5c-pre10b

**Comment by FlamesEC** [comment]
. . .

I..

The story is... I had a crash with a lot of mods, And i erased em all and immersive portals crashed... I erased the fabric API too

**Comment by FlamesEC** [comment]
Well.. it still crashes, but now i got a crash report :D

**Comment by FlamesEC** [comment]
[crash-2021-05-27_12.49.37-client.txt](https://github.com/TheOneTrueZandra/Figura/files/6555855/crash-2021-05-27_12.49.37-client.txt)

**Comment by Francy-chan** [comment]
The crash seems related with mod menu,
try updating your mods (all of them: figura, immersive portals, modmenu and fabric api)

**Comment by FlamesEC** [comment]
It worked! thanks :D
