### ISSUE TITLE
Minor spelling error under BlockBench Keywords on Figura Wiki

### ISSUE THREAD

**Issue by A1suya** [TheOneTrueZandra/Figura#125]
"ELTRA keyword defines the pivot and the model of the Elytra."
This line says _Eltra_, instead of the probably supposed _Elytra_.

Link to the line:
https://github.com/TheOneTrueZandra/Figura/wiki/Blockbench-Keywords#leftright_elytra

**Comment by Francy-chan** [comment]
oopsie, fixed!
