### ISSUE TITLE
Deactivating the player model makes skulls unable to render

### ISSUE THREAD

**Issue by FlamesEC** [TheOneTrueZandra/Figura#132]
By deactivating your normal player model, and wearing a _**skull/player head**_, you become unable to see that **_skull/player head_**

Not sure if it is a bug, just making sure though :D

![skullthing](https://user-images.githubusercontent.com/72460263/122136760-c5e34c00-ce08-11eb-93fe-8361c7872fc0.png)

**Comment by Francy-chan** [comment]
skulls are tied to the armor model
`armor_model.HEAD_ITEM.setEnabled(true)` makes skulls render
