### ISSUE TITLE
Second layer skin parts can't be disabled

### ISSUE THREAD

**Issue by bestsoft100** [TheOneTrueZandra/Figura#14]
vanillaModel.TORSO.setEnabled(false) works,
but
vanillaModel.JACKET.setEnabled(false) doesn't.

Also in the wiki the second head layer part is called HELMET, but its HAT in the code.

**Comment by TheOneTrueZandra** [comment]
This was fixed in [this commit](https://github.com/TheOneTrueZandra/Figura/commit/2e3987295c1d73a1d2a6b1f97412b33cba79638b) already.
