### ISSUE TITLE
Other players become invisble when a disabled part gets rendered

### ISSUE THREAD

**Issue by bestsoft100** [TheOneTrueZandra/Figura#15]
![2021-03-26_21 49 19](https://user-images.githubusercontent.com/49400900/112691446-a11caf80-8e7d-11eb-8561-fc5215cdfb0a.png)

I tried this in a LAN world and on Hypixel, it only happened to me in the LAN world

Also in the wiki the second head layer part is called HELMET, but its HAT in the code.

**Comment by TheOneTrueZandra** [comment]
Fixed in [this commit](https://github.com/TheOneTrueZandra/Figura/commit/d735ffdd3bbdae65142ce369dd0d10f3321aa86c)
