### ISSUE TITLE
Model transformation for head isn't showing up in-game

### ISSUE THREAD

**Issue by Chociily** [TheOneTrueZandra/Figura#16]
I've scaled and moved the model in Blockbench, but for some reason, it's shown off to the side in-game with its scaling lost. I might have done something wrong in Blockbench since I only started using it today and I don't know much, but I've tried to seek help and others didn't know what was causing the issue either. It might be a bug.

![image](https://user-images.githubusercontent.com/54920057/112693463-0f9a4700-8e57-11eb-96df-04ca6f24a359.png)
![image](https://user-images.githubusercontent.com/54920057/112693483-16c15500-8e57-11eb-9011-8a95a90a43b2.png)
![image](https://user-images.githubusercontent.com/54920057/112693500-22ad1700-8e57-11eb-83dc-77b0d30f3feb.png)

**Comment by TheOneTrueZandra** [comment]
Please check this in version 0.0.3 and reply back if it's fixed.

**Comment by Chociily** [comment]
> Please check this in version 0.0.3 and reply back if it's fixed.

It still does the same thing.

**Comment by TheOneTrueZandra** [comment]
Can you provide the files for your model?

**Comment by Chociily** [comment]
The issue has been resolved. Mistake on my end.
