### ISSUE TITLE
[wiki] Vanilla Model API wiki says HELMET instead of HAT

### ISSUE THREAD

**Issue by SHsuperCM** [TheOneTrueZandra/Figura#18]
https://github.com/TheOneTrueZandra/Figura/wiki/Vanilla-Model-API

Been trying to figure out why I couldnt disable the 2nd skin layer for the head so I went to the code and the api has it named as "HAT" and not "HELMET" like the wiki mentions.

**Comment by TheOneTrueZandra** [comment]
Fixed.
