### ISSUE TITLE
Models with no code do not unload ticking code from previously loaded models

### ISSUE THREAD

**Issue by SekoiaTree** [TheOneTrueZandra/Figura#2]
[no_code_issue.zip](https://github.com/TheOneTrueZandra/Figura/files/6208096/no_code_issue.zip)

Reproduction steps:
- Load up the "cloud" model
- Exit screen
- Load the "no_code" model
- Particles keep being emitted even though model is unloaded

This could be because there is no script, or because there is no function that overwrites it, idk.

**Comment by TheOneTrueZandra** [comment]
This is due to leftover assets never being cleared, will be fixed soon.

**Comment by TheOneTrueZandra** [comment]
Fixed in [this change.](https://github.com/TheOneTrueZandra/Figura/commit/4380e0a15b49f9c69d5ed96a6e0dded817cb0621#diff-89d5241a0cb9f921e56e4fc048816e0e09094010b2c86daf92afef4599855198R117)
