### ISSUE TITLE
Clicking on an avatar name that is active in the figura menu causes the avatar to turn invisible and display the file size incorrectly

### ISSUE THREAD

**Issue by epicdude324** [TheOneTrueZandra/Figura#22]
https://user-images.githubusercontent.com/81487072/112731430-8bef6180-8f0d-11eb-898d-b85625684e27.mov

**Comment by TheOneTrueZandra** [comment]
Invisibility should be fixed in [this commit](https://github.com/TheOneTrueZandra/Figura/commit/da4dce616c4b3327a928ea6e8f92b066e5888cff)

Filesize bug persists.
