### ISSUE TITLE
Other Player Second Layer Rendering Flat & Mis-sized

### ISSUE THREAD

**Issue by graysenpack** [TheOneTrueZandra/Figura#27]
![2021-03-28_21 19 22](https://user-images.githubusercontent.com/8918924/112842855-fb7d6200-906f-11eb-8255-23501f27bee4.png)
![Grogu_Comparison](https://user-images.githubusercontent.com/8918924/112843522-aa21a280-9070-11eb-8aae-7b6bcadc9d3c.png)

We are both using the exact same files (bbmodel, lua, & png). All are attached.

[Mando.zip](https://github.com/TheOneTrueZandra/Figura/files/6221972/Mando.zip)

When playing, the skin shows up normally for each of us individually, but renders flat & mis-sized for the other. I see him as flat & mis-sized (Grogu). He sees me as flat and mis-sized (Grogu).

The flat render is missing the second layer. The mis-sized Grogu and shut doors on the carrier are all blocks that are inflated in BlockBench.  Seems like these could be related since the second skin layer is also an inflation.

**Comment by graysenpack** [comment]
Playing around a bit more, this will also happen in my own view when I first load a world (single or server) and have this skin already set. Re-uploading it fixes it for myself.

We also tested this with other skins and got similar results

**Comment by TheOneTrueZandra** [comment]
Yes! Sorry I meant to reply to this earlier.

This is due to the fact that I forgot to save the "inflate" value to the avatar NBT when uploading to the server, and I forgot to load it.

I'll fix it this afternoon.

**Comment by TheOneTrueZandra** [comment]
This was fixed a few commits ago, forgot to close.
