### ISSUE TITLE
support parsing a binary model

### ISSUE THREAD

**Issue by DeltaNedas** [TheOneTrueZandra/Figura#33]
CBOR is considerably smaller than JSON.
while it may not be parsed by blockbench, it would be nice to support minified models that are much more compact (and thus can be more detailed for the same disk usage)

**Comment by TheOneTrueZandra** [comment]
All models are converted Compressed NBT directly once exported. That export is what determines the filesize of  the model, not the assets used to create it.

Unless you're specifically talking about source files, in which case, I don't really see a reason to support smaller source. JSon files aren't particularly large.

**Comment by DeltaNedas** [comment]
ah theyre already compressed when uploading, then it doesnt matter
