### ISSUE TITLE
Perhaps a peer to peer approach is better for longitivity 

### ISSUE THREAD

**Issue by boehs** [TheOneTrueZandra/Figura#4]
Instead of requesting data from a centralized server, why not request it from peers instead? free, and lasts for as long as the code works :)

**Comment by TheOneTrueZandra** [comment]
I've thought about this issue, but there's one main problem.

Obtaining the IP address of someone via Minecraft itself is very difficult, and I'd hate to invade people's privacy like that. P2P connections just have too much risk involved.

While I could filter all the traffic through the same server I use for files, it's absolutely not built for that kind of traffic.

Later, it's planned that we'll be adding the ability to use custom hosted servers, so by all means, you could implement this in one of those at some point if you like.

**Comment by TheOneTrueZandra** [comment]
I’m closing this issue, As I’ve stated, P2P is just not reasonable for this mod. It would help if the backend ever had problems, sure, but writing the backend to handle it while also making it secure is just not reasonable.

**Comment by Gappysona** [comment]
This is also resolved by the [serverside functionality](https://trello.com/c/TCrECsE9/16-serverside-functionality) coming in the future. :)
