### ISSUE TITLE
When reloading resource packs or enabling/disabling shaders, the textures on avatars turn into Steve.

### ISSUE THREAD

**Issue by Chociily** [TheOneTrueZandra/Figura#41]
I need to completely close and relaunch Minecraft in order to fix the issue.
![image](https://user-images.githubusercontent.com/54920057/113373230-63fe6480-9338-11eb-8896-214bb236d881.png)
![image](https://user-images.githubusercontent.com/54920057/113373354-a2941f00-9338-11eb-883d-560915793a14.png)
(how it's supposed to look)

**Comment by Redd56** [comment]
Note: also applies to server resource packs
Workaround. Reload resource packs and then reload avatar
