### ISSUE TITLE
crash when opening the figura gui

### ISSUE THREAD

**Issue by DeltaNedas** [TheOneTrueZandra/Figura#46]
[crash-2021-04-05_16.51.19-client.txt](https://github.com/TheOneTrueZandra/Figura/files/6259022/crash-2021-04-05_16.51.19-client.txt)

1. go into a world (sp or mp works)
2. click Figura
3. crash!

my amogus avatar still works before crashing though.

**Comment by TheOneTrueZandra** [comment]
Fran said this was fixed in [this PR](https://github.com/TheOneTrueZandra/Figura/pull/45) so I'll check again with that. Thanks for the report!
