### ISSUE TITLE
can't hide vanilla_model on multiplayer

### ISSUE THREAD

**Issue by DeltaNedas** [TheOneTrueZandra/Figura#50]
singleplayer mad drip
![Screenshot_08:45:46](https://user-images.githubusercontent.com/39013340/113676779-c054e180-96b4-11eb-9d16-a449c8235042.png)

multiplayer NOT drip
![Screenshot_08:45:16](https://user-images.githubusercontent.com/39013340/113676807-c5b22c00-96b4-11eb-906a-ee40e2f6f7bf.png)

code:
```lua
local function disable(model)
	for name, part in pairs(model) do
		part.setEnabled(false)
	end
end

-- hide the player model
disable(vanilla_model)
-- hide incorrect armor model
disable(armor_model)

```

strangely enough, works fine with `armor_model`.

**Comment by TheOneTrueZandra** [comment]
Should be fixed
