### ISSUE TITLE
Weird rendering in multiplayer

### ISSUE THREAD

**Issue by SlightlyPeckish** [TheOneTrueZandra/Figura#53]
Upon trying this mod with a friend in multiplayer (both using the latest prerelease 0.0.4f) the default skin doesn't hide and then sometimes does hide depending on whether I have an item in my hand or not or just the angle I'm looking at it 
Here is a gallery of different angles and bugs: [https://arxius.io/a/feebd6ad](https://arxius.io/a/feebd6ad) 
It is worth noting that all these skins work perfectly fine in singleplayer
I'm aware of this [issue](https://github.com/TheOneTrueZandra/Figura/issues/50) but thought I could add some more information to maybe help a bit
Clearing avatar doesn't always work it seems to glitch and show parts of models with wrong textures till a new model is selected and uploading models don't seem to change for the other person on the server
EDIT
In addition I have noticed that the player skin does not hide at all when you are not using a custom player model.

**Comment by TheOneTrueZandra** [comment]
Main issue with enable/disable state should be fixed in latest prerelease.

Still need to work on clearing avatar, that's an asset/server issue

**Comment by SlightlyPeckish** [comment]
Tested the latest version 0.0.4h and the issue with hiding the original skin in multiplayer appears to be fixed thanks for the great work :)

**Comment by SlightlyPeckish** [comment]
Tested the latest version 0.0.4h and the issue with hiding the original skin in multiplayer appears to be fixed thanks for the great work :)
