### ISSUE TITLE
getVelocity in the api is not multiplayer compat

### ISSUE THREAD

**Issue by Redd56** [TheOneTrueZandra/Figura#62]
getVelocity only works for your player, and not for other players, this is due to mojank more than likely. 
a workaround in lua looks like
velocity = {player.getPos()[1] - lastpos[1], player.getPos()[2] - lastpos[2], player.getPos()[3] - lastpos[3]}
lastpos = player.getPos()
would be nice if it was implemented into the api instead of the mojank way (obviously it would need to be changed some since different languages and all.)

**Comment by Redd56** [comment]
instanced per entity obviously

**Comment by TheOneTrueZandra** [comment]
This is unfixable, it’s a behavior of vanilla and what data is synced. We should probably remove it, in all honesty, and force people to calculate it manually, since that does more or less work. Regardless, the issue can’t be fixed, so, closing.

**Comment by Redd56** [comment]
K
