### ISSUE TITLE
Model won't render at the right place

### ISSUE THREAD

**Issue by ElieGonzales** [TheOneTrueZandra/Figura#65]
I made a model that is supposed to replace the head, using the group HEAD, but it isn't centered properly.
![2021-04-17_08 18 03](https://user-images.githubusercontent.com/79369230/115112906-9c678a80-9f55-11eb-962b-68402556e2bb.png)

**Comment by TheOneTrueZandra** [comment]
This isn't a bug. You need to center it in blockbench.

**Comment by ElieGonzales** [comment]
> This isn't a bug. You need to center it in blockbench.

How am I supposed to center it? it is on 0 0 0
