### ISSUE TITLE
Disabling the vanilla model doesn't work for other players

### ISSUE THREAD

**Issue by NotNite** [TheOneTrueZandra/Figura#66]
This loop:
```lua
for key, value in pairs(vanilla_model) do
    value.setEnabled(false)    
end
```
doesn't seem to work for other players in a multiplayer server.
![](https://xboxlive.party/i/mi6k44oh.png)
![](https://totallynotavir.us/i/rbomkp5s.png)

**Comment by TheOneTrueZandra** [comment]
This is not a bug. By default, disabling the vanilla model on another player is disabled to prevent griefing. You need to either allow the user to have that permission in the trust menu, or move them to a group that allows it.

**Comment by NotNite** [comment]
We both have each other in the Friend category, though? Vanilla Avatar Changes is checked for our permission levels.

**Comment by TheOneTrueZandra** [comment]
Are you using the latest prerelease or 0.0.4? 0.0.4 has a lot of bugs related to the enable state being incorrectly carried

**Comment by NotNite** [comment]
We both made sure we had the most recent prerelease (0.0.4t).

**Comment by TheOneTrueZandra** [comment]
The yes, I’d just check and be sure that the trust system is actually set up correctly (make sure that vanilla modifications is GREEN for them)

**Comment by NotNite** [comment]
We've double checked, but in the process we realized something else - our scripts aren't actually running. We both have parts of our avatar scripted to do things that used to work a few days ago (before we updated) that are now broken. Perhaps a recent commit broke scripts?

**Comment by TheOneTrueZandra** [comment]
Re-cap, this is due to the script cleanup being incorrect in the syntax for multi-line comments in lua. Will be fixed shortly.
